opentracing:
  haystack:
    dispatchers:
      agent:
        enabled: true
        host: ${HAYSTACK_AGENT_HOST:localhost}
        port: 35000
haystack:
 blobs:
  enabled: true
  store:
   name: agent
   host: ${HAYSTACK_AGENT_HOST:localhost}
   port: 35001
